### ISSUE TITLE
Creating a block python to implement multiplier in Gnuradio

### ISSUE THREAD

**Issue by PHDsaoudi** [mhostetter/gr-detector#1]
I'm creating module multiplier, after that building and install the block named multiplier_ff with these instruction allowed by the site https://wiki.gnuradio.org/index.php/Guided_Tutorial_GNU_Radio_in_Python :
gr_modtool newmod multiplier
cd gr-tutorial
ls
gr_modtool add -t sync -l python

After that, I edited file multiplier.py , qa_multiplier_ff.py and multiplier_multiplier_ff.block.yml
Finally i run python3 qa_multiplier_ff.py; the test is acheived succefully
crm@crm-X570-UD:~/gr-multiplier/python/multiplier$ python3 qa_multiplier_ff.py
DEPRECATED: Using filename with gr_unittest does no longer have any effect.
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
After that, build and install projhect with these instructions:
cd gr-multiplier
mkdir build
cd build
cmake ..
make
sudo make install
sudo ldconfig

However when i run gnuradio-companion , there is an error:
<<< Welcome to GNU Radio Companion 3.10.8.0-rc2 >>>

Block paths:
	/usr/local/share/gnuradio/grc/blocks
>>> Check: /usr/local/share/gnuradio/grc/blocks/multiplier_multiplier_ff.block.yml
>>> FlowGraph Error: mapping values are not allowed here
  in "/usr/local/share/gnuradio/grc/blocks/multiplier_multiplier_ff.block.yml", line 17, column 16

Please help me to solve this problem and make this bloc available in gnuradio

**Comment by mhostetter** [comment]
Your issues are unrelated to my repository. Please direct your questions to the [GNU Radio mailing list](https://wiki.gnuradio.org/index.php?title=ReportingErrors).
