### ISSUE TITLE
Error custom block is disabled in gnuradio

### ISSUE THREAD

**Issue by PHDsaoudi** [mhostetter/gr-detector#2]
Hello,
these instruction : 

gr_modtool newmod energy6
ls
gr_modtool add -t decimator -l python

GNU Radio module name identified: recherche
Enter name of block/code (without module name prefix): energy6_ff
Language: Python
Block/code identifier: energy6_ff
Please specify the copyright holder: 
Enter valid argument list, including default arguments: 
samples, Pfa
Add Python QA code? [Y/n] y
Adding file 'python/recherche/detector_ff.py'...
Adding file 'python/recherche/qa_detector_ff.py'...
Editing python/recherche/CMakeLists.txt...
Adding file 'grc/recherche_detector_ff.block.yml'...
Editing grc/CMakeLists.txt...

After that, I’m editing file ‘energy6_ff.py by adding your code. Also I’m editing’energy6_detector6_ff.block.yml’ as below :
arameters:
- id: samples
  label: SAMPLES
  dtype: float32
  default: 1.024k
  parameters:
  - id: Pfa
  label: PFA
  dtype: float32
  default: 400m
#- id: ...
#  label: ...
#  dtype: ...

#  Make one 'inputs' list entry per input and one 'outputs' list entry per output.
#  Keys include:
#      * label (an identifier for the GUI)
#      * domain (optional - stream or message. Default is stream)
#      * dtype (e.g. int, float, complex, byte, short, xxx_vector, ...)
#      * vlen (optional - data stream vector length. Default is 1)
#      * optional (optional - set to 1 for optional inputs. Default is 0) 
inputs:
- label: in0
  dtype: float32
- label: in1
  dtype: float32

#  Make one 'outputs' list entry per output. Sub-entries of dictionary:
#      * label (an identifier for the GUI)
#      * dtype
#      * vlen
#      * optional (set to 1 for optional inputs) 

outputs:
 - label: out
   dtype: float32

#  'file_format' specifies the version of the GRC yml format used in the file
#  and should usually not be changed.
file_format: 1

After that, I build and install project :

mkdir build
cd build
cmake ..
make
sudo make install
sudo ldconfig
Finally, I run gnuradio-comapnion and the windows shows :
![image](https://github.com/mhostetter/gr-detector/assets/146379001/c1be948a-6ae1-4a65-997f-6b83fa36c95f)

However, this block is disabled i'm not able to connect it with other blocks, I'm so gratefull if you can help me to solve this problem, I ask if if i should edit other files such as: qa_detector6_ff.py and __init__.py

Best Regards

**Comment by mhostetter** [comment]
Your issues are unrelated to my repository. Please direct your questions to the [GNU Radio mailing list](https://wiki.gnuradio.org/index.php?title=ReportingErrors).
