### ISSUE TITLE
ModuleNotFoundError: No module named 'gnuradio.detection5.energy_detection_ff'

### ISSUE THREAD

**Issue by PHDsaoudi** [mhostetter/gr-detector#3]
Hello,
 I created a block python named«energy_detection_ff» and it is displayed correctly in gnuradio, However when i run and execute code ; it shows an error :

from gnuradio import detection5
  File "/usr/local/lib/python3.8/dist-packages/gnuradio/detection5/__init__.py", line 23, in <module>
    from .energy_detection_ff import energy_detection_ff
ModuleNotFoundError: No module named 'gnuradio.detection5.energy_detection_ff'

And the file of __init__.py is shown as below :

#
# Copyright 2008,2009 Free Software Foundation, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

# The presence of this file turns this directory into a Python package

'''
This is the GNU Radio DETECTION5 module. Place your Python package
description here (python/__init__.py).
'''
import os

# import pybind11 generated symbols into the detection5 namespace
try:
    # this might fail if the module is python-only
    from .detection5_python import *
except ModuleNotFoundError:
    pass

# import any pure python here
from .energy_detection_ff import energy_detection_ff
#

Please help me to solve this problem, i asked if i shoud edit the file __init__.py, I’m so gratefull to help me

**Comment by mhostetter** [comment]
Your issues are unrelated to my repository. Please direct your questions to the [GNU Radio mailing list](https://wiki.gnuradio.org/index.php?title=ReportingErrors).
