### ISSUE TITLE
ModuleNotFoundError: No module named 'gnuradio.detection5.energy_detection_ff'

### ISSUE THREAD

**Issue by PHDsaoudi** [mhostetter/gr-detector#4]
Hello,
 I created a block python named«energy_detection_ff» and it is displayed correctly in gnuradio, However when i run and execute code ; it shows an error :
from gnuradio import detection5
  File "/usr/local/lib/python3.8/dist-packages/gnuradio/detection5/__init__.py", line 23, in <module>
    from .energy_detection_ff import energy_detection_ff
ModuleNotFoundError: No module named 'gnuradio.detection5.energy_detection_ff'

And the file of __init__.py is shown as below :
![ab](https://github.com/mhostetter/gr-detector/assets/146379001/c11a75b8-0ad8-464a-af2a-fdead57e4e96)

Please help me to solve this problem, i asked if i shoud edit the file __init__.py, I’m so gratefull to help me

**Comment by mhostetter** [comment]
Your issues are unrelated to my repository. Please direct your questions to the [GNU Radio mailing list](https://wiki.gnuradio.org/index.php?title=ReportingErrors).
